# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aron/2022/akis_main/my_first_program

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aron/2022/akis_main/my_first_program

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aron/2022/akis_main/my_first_program/CMakeFiles /home/aron/2022/akis_main/my_first_program//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aron/2022/akis_main/my_first_program/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ThirdFile

# Build rule for target.
ThirdFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThirdFile
.PHONY : ThirdFile

# fast build rule for target.
ThirdFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/build
.PHONY : ThirdFile/fast

#=============================================================================
# Target rules for targets named SecondFile

# Build rule for target.
SecondFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SecondFile
.PHONY : SecondFile

# fast build rule for target.
SecondFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/build
.PHONY : SecondFile/fast

#=============================================================================
# Target rules for targets named FirstFile

# Build rule for target.
FirstFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FirstFile
.PHONY : FirstFile

# fast build rule for target.
FirstFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/build
.PHONY : FirstFile/fast

first_file.o: first_file.cc.o
.PHONY : first_file.o

# target to build an object file
first_file.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/first_file.cc.o
.PHONY : first_file.cc.o

first_file.i: first_file.cc.i
.PHONY : first_file.i

# target to preprocess a source file
first_file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/first_file.cc.i
.PHONY : first_file.cc.i

first_file.s: first_file.cc.s
.PHONY : first_file.s

# target to generate assembly for a file
first_file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/first_file.cc.s
.PHONY : first_file.cc.s

second_file.o: second_file.cc.o
.PHONY : second_file.o

# target to build an object file
second_file.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/second_file.cc.o
.PHONY : second_file.cc.o

second_file.i: second_file.cc.i
.PHONY : second_file.i

# target to preprocess a source file
second_file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/second_file.cc.i
.PHONY : second_file.cc.i

second_file.s: second_file.cc.s
.PHONY : second_file.s

# target to generate assembly for a file
second_file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/second_file.cc.s
.PHONY : second_file.cc.s

src/first_test_header.o: src/first_test_header.cc.o
.PHONY : src/first_test_header.o

# target to build an object file
src/first_test_header.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/src/first_test_header.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/src/first_test_header.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/src/first_test_header.cc.o
.PHONY : src/first_test_header.cc.o

src/first_test_header.i: src/first_test_header.cc.i
.PHONY : src/first_test_header.i

# target to preprocess a source file
src/first_test_header.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/src/first_test_header.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/src/first_test_header.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/src/first_test_header.cc.i
.PHONY : src/first_test_header.cc.i

src/first_test_header.s: src/first_test_header.cc.s
.PHONY : src/first_test_header.s

# target to generate assembly for a file
src/first_test_header.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/src/first_test_header.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondFile.dir/build.make CMakeFiles/SecondFile.dir/src/first_test_header.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FirstFile.dir/build.make CMakeFiles/FirstFile.dir/src/first_test_header.cc.s
.PHONY : src/first_test_header.cc.s

third_file.o: third_file.cc.o
.PHONY : third_file.o

# target to build an object file
third_file.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/third_file.cc.o
.PHONY : third_file.cc.o

third_file.i: third_file.cc.i
.PHONY : third_file.i

# target to preprocess a source file
third_file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/third_file.cc.i
.PHONY : third_file.cc.i

third_file.s: third_file.cc.s
.PHONY : third_file.s

# target to generate assembly for a file
third_file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThirdFile.dir/build.make CMakeFiles/ThirdFile.dir/third_file.cc.s
.PHONY : third_file.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FirstFile"
	@echo "... SecondFile"
	@echo "... ThirdFile"
	@echo "... first_file.o"
	@echo "... first_file.i"
	@echo "... first_file.s"
	@echo "... second_file.o"
	@echo "... second_file.i"
	@echo "... second_file.s"
	@echo "... src/first_test_header.o"
	@echo "... src/first_test_header.i"
	@echo "... src/first_test_header.s"
	@echo "... third_file.o"
	@echo "... third_file.i"
	@echo "... third_file.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

